import AppKit

/// Localization shim for the ported macshot capture UI.
///
/// macshot resolves copy through `L(_:)` with human-readable English keys.
/// The product is Chinese-first, so the shim maps every key to Simplified
/// Chinese and falls back to the key itself for anything unmapped.
private let localizedCaptureStrings: [String: String] = [
    // Selection hints
    "Drag to select  ·  Click for full screen": "拖拽框选  ·  单击全屏",
    "Click a window  ·  Drag for custom area  ·  F for full screen": "点击窗口吸附  ·  拖拽自定区域  ·  F 全屏",
    "Hold Space to move. Release to annotate and edit": "按住空格移动选区，松开开始标注编辑",
    "Hold Space to move. Release to finish": "按住空格移动选区，松开完成截图",
    "Release to finish": "松开完成截图",
    "Hold 1 auto-vertical  ·  Hold 2 auto-horizontal": "按住 1 自动纵向  ·  按住 2 自动横向",
    "Window snap: ": "窗口吸附：",
    "  (Tab to toggle)": "（按 Tab 切换）",
    "Right-click to copy": "右键复制",
    "%d seconds": "%d 秒",

    // Tools
    "Rectangle": "矩形",
    "Ellipse": "椭圆",
    "Line": "直线",
    "Arrow": "箭头",
    "Pencil": "铅笔",
    "Pencil (Draw)": "铅笔（绘制）",
    "Marker": "马克笔",
    "Highlight": "高亮",
    "Highlight (Spotlight)": "高亮（聚光灯）",
    "Blur": "模糊",
    "Censor": "遮蔽",
    "Censor (Pixelate / Blur / Solid)": "遮蔽（马赛克 / 模糊 / 纯色）",
    "Loupe": "放大镜",
    "Magnify (Loupe)": "放大镜",
    "Measure": "测量",
    "Measure (px)": "测量（像素）",
    "Number": "序号",
    "Stamp": "贴纸",
    "Stamp / Emoji": "贴纸 / 表情",
    "Text": "文字",
    "Color": "颜色",
    "Color Picker": "取色器",
    "Crop": "裁剪",
    "Fit Canvas": "适配画布",
    "Flip": "翻转",
    "Flip Horizontal": "水平翻转",
    "Flip Vertical": "垂直翻转",
    "Invert Colors": "反色",
    "Draw:": "绘制：",
    "Fill": "填充",
    "Outline": "描边",
    "Stroke": "笔触",
    "Pressure": "压感",
    "Smooth": "平滑",
    "Radius": "半径",
    "Dim": "压暗",
    "Faces": "人脸",
    "People": "人物",
    "All Text": "全部文字",
    "Text Only": "仅文字",
    "PII": "敏感信息",
    "Smart": "智能",
    "All": "全部",
    "None": "无",

    // Actions
    "Copy": "复制",
    "Copy to clipboard": "复制到剪贴板",
    "Copied %@": "已复制 %@",
    "Set color %@": "已设为颜色 %@",
    "Save": "保存",
    "Save As...": "另存为…",
    "Save to": "保存到",
    "Save to default folder": "保存到默认文件夹",
    "Ask where to save": "询问保存位置",
    "Choose a folder": "选择文件夹",
    "Pin": "贴图",
    "Pin (floating window)": "贴图（悬浮窗）",
    "OCR & QR": "OCR 与二维码",
    "Undo": "撤销",
    "Redo": "重做",
    "Delete": "删除",
    "Done": "完成",
    "Cancel": "取消",
    "Move Selection": "移动选区",
    "Adjust": "调整",
    "Adjust (Image Effects)": "调整（图像效果）",
    "Adjustments": "调整",
    "Reset": "重置",
    "More Emojis": "更多表情",
    "Show in Finder": "在 Finder 中显示",
    "Open editor": "打开编辑器",
    "Open in Editor": "在编辑器中打开",
    "Open Settings": "打开设置",
    "Load Image": "载入图片",
    "Add Capture": "追加截图",
    "Size": "尺寸",
    "Zoom": "缩放",
    "Zoom In": "放大",
    "Zoom Out": "缩小",
    "Hide controls": "隐藏控件",
    "Presets": "预设",
    "Freeform": "自由",
    "Aspect ratio": "宽高比",
    "Aspect ratio & resolution presets": "宽高比与分辨率预设",
    "Keep ratio for next captures": "后续截图保持该比例",
    "Resolution": "分辨率",
    "Custom · %@": "自定义 · %@",
    "Limit to selection": "仅限选区内",
    "Space": "空格",
    "On": "开",
    "ON": "开",
    "OFF": "关",
    "Auto Scroll": "自动滚动",
    "Auto:": "自动：",
    "Scrolling...": "滚动截图中…",
    "Start:": "开始：",
    "Stop": "停止",
    "Delay:": "延迟：",
    "Start Recording": "开始录制",
    "Record": "录屏",
    "Record screen": "录制屏幕",
    "Cancel Recording": "取消录制",
    "Recording Settings": "录制设置",
    "Record System Audio": "录制系统声音",
    "Record Microphone": "录制麦克风",
    "Show Keystrokes": "显示按键",
    "All Keystrokes": "全部按键",
    "Highlight Mouse Clicks": "高亮鼠标点击",
    "Webcam Overlay": "摄像头浮窗",
    "Camera Access Required": "需要摄像头权限",
    "Microphone Access Required": "需要麦克风权限",
    "macshot needs camera permission for the webcam overlay. Open System Settings to grant access.": "Yaomao 需要摄像头权限才能使用摄像头浮窗，请前往系统设置授权。",
    "macshot needs microphone permission to record voice audio. Open System Settings to grant access.": "Yaomao 需要麦克风权限才能录制声音，请前往系统设置授权。",

    // Image effects & beautify
    "Beautify": "美化",
    "Gradient Style": "渐变样式",
    "Brightness": "亮度",
    "Contrast": "对比度",
    "Saturation": "饱和度",
    "Sharpness": "锐化",
    "Padding": "内边距",
    "Shadow": "阴影",
    "Refined": "精致",
    "Upload": "上传",
    "Share": "分享",
    "Translate": "翻译",
    "Remove Background": "移除背景",
    "Auto-Redact sensitive data": "自动遮蔽敏感信息",
    "Upload to Google Drive?": "上传到 Google Drive？",
    "Upload to imgbb.com?": "上传到 imgbb.com？",
    "Upload to S3?": "上传到 S3？",
    "Your screenshot will be uploaded.": "截图将被上传。",
    "Confirm before upload": "上传前确认",
    "Shortcuts Only": "仅快捷键",
    "Same as screenshots": "与截图一致",
    "Units": "单位",
    "FPS:": "帧率：",
    "When done:": "完成后：",
    "Cam pos:": "摄像头位置：",
    "Cam shape:": "摄像头形状：",
    "Cam size:": "摄像头大小：",
    "Background removal failed — no clear subject found.": "移除背景失败——未找到清晰主体。",
]

func L(_ key: String) -> String {
    localizedCaptureStrings[key] ?? key
}

// MARK: - CaptureSound

/// Shutter/copy feedback sound for the capture flow.
///
/// Replaces macshot's `AppDelegate.captureSound` so the ported overlay does
/// not depend on the host app delegate.
enum CaptureSound {
    static let sound: NSSound? = {
        guard let url = URL(string: "/System/Library/Sounds/Pop.aiff") else { return nil }
        return NSSound(contentsOf: url, byReference: true)
    }()
}
